# docker-compose.yml

version: '3.8'

services:
  # React App
  web:   
    container_name: new-app
    build: .
    image: new   
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: yarn dev
